name: Build Windows EXE
on: [push, workflow_dispatch]

jobs:
  build:
    # بنستخدم سيرفر ويندوز عشان نضمن التوافق 100%
    runs-on: windows-latest 

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Packaging App to EXE
        run: |
          # أمر التحويل لملف EXE واحد
          flet pack main.py --name "SaoudApp"

      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: Saoud-Windows-EXE
          path: dist/*.exe
